<div class ="center-block">


    <center><h1> Login</h1></center>

<?php echo validation_errors();   //This shows on screen the validation errors that are generated by the validation rules in LoginController?>

<?php echo form_open('LoginController/checklogin'); //This makes the page run the checklogin function upon submission ?>

 <?php
                        $attr = array (
                        'class'=>'register_form'
                        ); //I can set the dynamics of the fieldset here. Such as centerd and so forth.


echo form_fieldset('', $attr); //
echo form_open(''); //This makes the page run the checklogin function upon submission ?>

Username: <br/>
<input type='text' name='username'/><br/>

Password: <br/>
<input type='text' name='password'/><br/>

<input type='submit' value='Login' name='submit'/>


</div>
    
 <?php echo form_close(); 
echo form_fieldset_close();
?>